# Generated by Django 5.0.4 on 2024-04-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_ID', models.CharField(max_length=10)),
                ('Street_Address', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Zip_Code', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
    ]
