# Generated by Django 5.0.4 on 2024-04-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Type',
            fields=[
                ('address_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('DCode', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('Family_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Family_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('organization_id', models.IntegerField()),
                ('Address_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Person_ID', models.AutoField(primary_key=True, serialize=False)),
                ('LName', models.CharField(max_length=100)),
                ('FName', models.CharField(max_length=100)),
                ('age', models.FloatField(blank=True, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TF', 'Transgender Female'), ('TM', 'Transgender Male'), ('O', 'Other')], max_length=2)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Religion', models.CharField(blank=True, max_length=100)),
                ('DOD', models.DateField(blank=True, null=True)),
                ('YearsEducation', models.CharField(blank=True, max_length=100)),
                ('Ethnicity', models.CharField(blank=True, max_length=100)),
                ('Image', models.CharField(blank=True, max_length=100)),
                ('Genogram_Image', models.CharField(blank=True, max_length=100)),
                ('Ecomap_Image', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_ID', models.IntegerField()),
                ('E_Mail', models.CharField(help_text='TODO: remove this column in favor of person.email', max_length=100)),
                ('address_type_id', models.IntegerField()),
                ('Person_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person_Historical_Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dcode', models.IntegerField()),
                ('Person_ID', models.IntegerField()),
                ('Diagnosed_Date', models.CharField(max_length=100)),
                ('Recovery_Status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person_Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField()),
                ('Relationship_Type', models.CharField(max_length=100)),
                ('Relationship_Status', models.CharField(max_length=100)),
                ('Person_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Person_ID', models.IntegerField()),
            ],
        ),
    ]
