# Generated by Django 5.0.4 on 2024-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Person_ID', models.AutoField(primary_key=True, serialize=False)),
                ('LName', models.CharField(max_length=100)),
                ('FName', models.CharField(max_length=100)),
                ('age', models.FloatField(blank=True, null=True)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('TF', 'Transgender Female'), ('TM', 'Transgender Male'), ('O', 'Other')], max_length=2)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Religion', models.CharField(blank=True, max_length=100)),
                ('DOD', models.DateField(blank=True, null=True)),
                ('YearsEducation', models.CharField(blank=True, max_length=100)),
                ('Ethnicity', models.CharField(blank=True, max_length=100)),
                ('Image', models.CharField(blank=True, max_length=100)),
                ('Genogram_Image', models.CharField(blank=True, max_length=100)),
                ('Ecomap_Image', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255)),
            ],
        ),
    ]
