# Generated by Django 5.0.4 on 2024-04-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address_Type',
        ),
        migrations.DeleteModel(
            name='Diagnostic',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Organization_Address',
        ),
        migrations.DeleteModel(
            name='Person_Address',
        ),
        migrations.DeleteModel(
            name='Person_Historical_Diagnostic',
        ),
        migrations.DeleteModel(
            name='Person_Organization',
        ),
        migrations.DeleteModel(
            name='Person_Phone',
        ),
    ]
