# Generated by Django 5.0.4 on 2024-04-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_delete_address_type_delete_diagnostic_delete_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_ID', models.CharField(max_length=100)),
                ('E_Mail', models.CharField(help_text='TODO: remove this column in favor of person.email', max_length=100)),
                ('address_type_id', models.CharField(max_length=100)),
                ('Person_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person_Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(max_length=100)),
                ('Relationship_Type', models.CharField(max_length=100)),
                ('Relationship_Status', models.CharField(max_length=100)),
                ('Person_ID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person_Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Number', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Person_ID', models.CharField(max_length=100)),
            ],
        ),
    ]
